# The Basics of NumPy Arrays

## NumPy Array Attributes

In [206]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [51]:
print("Matrix x1: ",'\n',x1,'\n')
print("Matrix x2: ",'\n',x2,'\n')
print("Matrix x3: ",'\n',x3)

Matrix x1:  
 [4 3 4 4 8 4] 

Matrix x2:  
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

Matrix x3:  
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [47]:
print("Printing data regarding x3")
print(x3.ndim)
print(x3.shape)
print(x3.size)


Printing data regarding x3
3
(3, 4, 5)
60


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [49]:
s=np.arange(1,31).reshape(5,6)#printing 5X6 matrix
print(s)
print("item size : ",s.itemsize) #printing item size of s matirx
print("nbytes : ",s.nbytes)# Total bytes taken by elemnts of array.

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
item size :  4
nbytes :  120


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [53]:
d1 = np.random.randint(10, size=6)
d1

array([3, 7, 5, 5, 0, 1])

In [54]:
d1[0]# using *iv index form o to n

3

In [55]:
d1[1]# using *iv index form o to n

7

To index from the end of the array, you can use negative indices:

In [56]:
d1[-1]# to acces last element using -ive index in array len of 6

1

In [57]:
d1[-6]# to acces 1st element using -ive index in array len of 6 

3

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [58]:
a = np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])
a

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [59]:
a[0,0]

3

In [60]:
a[2,0]

1

In [61]:
a[1,0]

7

Values can also be modified using any of the above index notation:

In [63]:
a[0,0]=12 #updating the 1st element of matrix by providing row and col index no.
a

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [82]:
b=np.array([3, 0, 3, 3, 7, 9])
print(b)
b=np.append (b,[10,2.4])# here 1st i have append 10 and check the type is int as we append a floting value its changes all element to float value.
b

[3 0 3 3 7 9]


array([ 3. ,  0. ,  3. ,  3. ,  7. ,  9. , 10. ,  2.4])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [84]:
demo=np.arange(0,10)
demo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
demo[0:5]# printing(0 to 4 elements )

array([0, 1, 2, 3, 4])

In [87]:
demo[5:]# printing from 5 to end 

array([5, 6, 7, 8, 9])

In [89]:
demo[4:7]# printing (4,5,6) index goes to 1+ step ahead.

array([4, 5, 6])

In [96]:
demo[0:9:2]# :2 steps ahead and then print that element.

array([0, 2, 4, 6, 8])

In [97]:
demo[1::2]# :2 steps ahead and then print that element.

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [99]:
demo[::-1]# reverse an array by -ive indexing

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [116]:
demoo=demo[::-1]# 1st reverse the array and then apply slicing.
demoo[4::2]

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [118]:
multi=np.array([[12,  5,  2,  4],[ 7,  6,  8,  8],[ 1,  6,  7,  7]])
multi

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [119]:
multi[0:2,0:3] # printing sub matris.

array([[12,  5,  2],
       [ 7,  6,  8]])

In [123]:
multi[0::,0::2]# skipping 2nd col (5,6,6)

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [127]:
m=multi[::-1]
# m[::-1]      ####### NOT GEETING THIS ONE. 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [128]:
multi

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [131]:
multi[0:,0]

array([12,  7,  1])

In [132]:
multi[0,0:]

array([12,  5,  2,  4])

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [135]:
multi[[0]]# without slicing accessing 1st row.

array([[12,  5,  2,  4]])

### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [136]:
multi

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Let's extract a $2 \times 2$ subarray from this:

In [137]:
multi[0:2,0:2]

array([[12,  5],
       [ 7,  6]])

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [141]:
multi[0,0]=99
multi[0,1]=5
multi[1,0]=7
multi[1,1]=6
# print(multi)
multi[0:2,0:2]

array([[99,  5],
       [ 7,  6]])

In [156]:
multi1=np.array([[12,  5,  2,  4],[ 7,  6,  8,  8],[ 1,  6,  7,  7]])
# multi1
multi1[0,0]=99
multi1[0,1]=5
multi1[1,0]=7
multi1[1,1]=6
multi1

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [157]:
multi1

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [159]:
C_multi=multi1.copy()# here copied the matrix multi1

In [161]:
# C_multi

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
# which contains (99,5,7,6)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [163]:
multi1[0,0]=42
multi1[0,1]=5
multi1[1,0]=7
multi1[1,1]=6
print(multi1)
C_multi

[[42  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
# here we can clearly see that we have copied multi1 data to C_multi so, when we update multi1 data 
# , their is no change in C_multi as the original data is copied in C_multi

[[42  5]
 [ 7  6]]


In [164]:
C_multi

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [166]:
re=np.arange(1,10).reshape(3,3)
re

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [169]:
re1=re[[0]]
re1

array([[1, 2, 3]])

In [171]:
re1.reshape(1,3)# reshaping in 1 row 3 col

array([[1, 2, 3]])

In [172]:
re1.reshape(3,1)# reshaping in 3 row 1 col

array([[1],
       [2],
       [3]])

In [173]:
re1.reshape(3,1)# reshaping in 3 row 1 col

array([[1],
       [2],
       [3]])

We will see this type of transformation often throughout the remainder of the book.

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [176]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
# Complete the code ???????
np.concatenate((x,y)) # concatenating x and y array in one array.

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [177]:
# Complete the code ???????
z = np.array([99,99,99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [179]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [183]:
# concatenate along the first axis
np.concatenate([grid,grid]) # here concatenating grid into grid.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [185]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid,grid], axis=1) # here concatinating along axis 1 whic is col.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [202]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])          # vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [204]:
y = np.array([[7,99],[4,99]])
z=np.array([[9,8],[6,5]])            # horizontally stack the arrays
np.hstack([z,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [191]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [207]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [208]:
upper, lower = np.vsplit(grid,2)# performing vertical split
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [209]:
left, right = np.hsplit(grid,2) # performing horizontal split
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


----------------------END-------------------